module.exports=[
  "Azarovs Resting Place",
  "Blood Lodge",
  "Gas Heaven",
  "Wretched Shop",
  "Wreckers Yard",
  "Fractured Cowshed",
  "Rancid Abattoir",
  "Rotten Fields",
  "The Thompson House",
  "Torment Creek",
  "Disturbed Ward",
  "Father Campbells Chapel",
  "Coal Tower",
  "Groaning Storehouse",
  "Ironworks of Misery",
  "Shelter Woods",
  "Suffocation Pit",
  "Lampkin Lane",
  "Badham Preschool I",
  "Badham Preschool II",
  "Badham Preschool III",
  "Badham Preschool IV",
  "Badham Preschool V",
  "The Pale Rose",
  "Grim Pantry",
  "Treatment Theatre",
  "Mothers Dwelling",
  "The Temple of Purgation",
  "The Game",
  "Family Residence",
  "Sanctum of Wrath",
  "Mount Ormond Resort",
  "Dead Dawg Saloon",
  "Midwich Elementary School",
  "Raccoon City Police Station East Wing",
  "Raccoon City Police Station West Wing",
  "Eyrie of Crows",
  "Garden of Joy",
  "Shattered Square",
  "Toba Landing",
  "Nostromo Wreckage",
  "Greenville Square",
  "Forgotten Ruins",
  "The Underground Complex"
]