(()=>{
  'use strict';

  const SOLID_COLORS=[
    ['#22c55e','Verde'],['#facc15','Amarelo'],['#3b82f6','Azul'],['#ef4444','Vermelho'],
    ['#ec4899','Rosa'],['#a855f7','Roxo'],['#06b6d4','Ciano'],['#f97316','Laranja']
  ];
  let T=null,lang='pt',capture=null;
  const $=id=>document.getElementById(id);

  const TX={
    pt:{tab:'1V1 TIMER',show:'Mostrar overlay',hide:'Ocultar overlay',players:'Players',score:'Placar',styles:'Estilos',hotkeys:'Atalhos do 1v1 Timer',appearance:'Aparência',reset:'Resetar partida',startStop:'Iniciar / Parar / Pontuar',swap:'Trocar player',resetKey:'Resetar',opacity:'OPACIDADE DO FUNDO',scale:'ESCALA',accent:'Cor de destaque',accentHint:'Uma cor controla o destaque. O restante do overlay permanece branco e cinza.',custom:'Personalizado',rainbow:'Colorido',workflow:'Como funciona',workflowText:'O atalho principal inicia o player selecionado. Pressione novamente para parar e salvar o tempo. Depois troque para o outro player pelo atalho de troca, ou ative a troca automática. Repita. Com os dois tempos salvos, pressione novamente o atalho principal para comparar e dar o ponto automaticamente ao menor tempo.',ms:'Milissegundos aparecem somente aqui no aplicativo e continuam sendo usados para desempatar. No overlay ficam ocultos.',ready:'Pronto para',timing:'Cronometrando',saved:'Tempo salvo. Troque para',savedAuto:'Tempo salvo. Player trocado automaticamente para',both:'Os dois tempos estão salvos. Pressione o atalho principal para comparar e pontuar.',winner:'Ponto para',tie:'Empate exato — nenhum ponto.',setKey:'Clique e pressione uma tecla…',internalConflict:'Esse botão já existe em outro atalho',systemConflict:'Não foi possível usar essa tecla. Ela pode estar reservada pelo Windows ou por outro programa.',autoSwap:'Trocar player automaticamente ao parar',autoSwapHint:'Ativado: ao salvar o primeiro tempo, o segundo player já fica selecionado.',style0:'Vertical Edge',style1:'Vertical Core',style2:'Horizontal Line',style3:'Horizontal Split',style4:'Glass Arc',style5:'Glass Float',vertical:'Vertical',horizontal:'Horizontal',glass:'Glass'},
    en:{tab:'1V1 TIMER',show:'Show overlay',hide:'Hide overlay',players:'Players',score:'Score',styles:'Styles',hotkeys:'1v1 Timer Hotkeys',appearance:'Appearance',reset:'Reset match',startStop:'Start / Stop / Score',swap:'Swap player',resetKey:'Reset',opacity:'BACKGROUND OPACITY',scale:'SCALE',accent:'Accent color',accentHint:'One color controls the highlight. The rest of the overlay stays white and gray.',custom:'Custom',rainbow:'Rainbow',workflow:'How it works',workflowText:'The main shortcut starts the selected player. Press it again to stop and save the time. Then switch to the other player with the swap shortcut, or enable automatic switching. Repeat. With both times saved, press the main shortcut again to compare and automatically award the point to the faster time.',ms:'Milliseconds are shown only here in the app and are still used as the tiebreaker. They stay hidden on the overlay.',ready:'Ready for',timing:'Timing',saved:'Time saved. Swap to',savedAuto:'Time saved. Player automatically switched to',both:'Both times are saved. Press the main shortcut to compare and score.',winner:'Point for',tie:'Exact tie — no point.',setKey:'Click and press a key…',internalConflict:'This key is already used by another shortcut',systemConflict:'Could not use that key. It may be reserved by Windows or another program.',autoSwap:'Automatically swap player when stopped',autoSwapHint:'On: after the first time is saved, the other player is selected automatically.',style0:'Vertical Edge',style1:'Vertical Core',style2:'Horizontal Line',style3:'Horizontal Split',style4:'Glass Arc',style5:'Glass Float',vertical:'Vertical',horizontal:'Horizontal',glass:'Glass'},
    es:{tab:'1V1 TIMER',show:'Mostrar overlay',hide:'Ocultar overlay',players:'Jugadores',score:'Marcador',styles:'Estilos',hotkeys:'Atajos del 1v1 Timer',appearance:'Apariencia',reset:'Reiniciar partida',startStop:'Iniciar / Parar / Puntuar',swap:'Cambiar jugador',resetKey:'Reiniciar',opacity:'OPACIDAD DEL FONDO',scale:'ESCALA',accent:'Color de destaque',accentHint:'Un color controla el destaque. El resto del overlay permanece blanco y gris.',custom:'Personalizado',rainbow:'Colorido',workflow:'Cómo funciona',workflowText:'El atajo principal inicia al jugador seleccionado. Presiónalo otra vez para detener y guardar el tiempo. Luego cambia al otro jugador con el atajo de cambio, o activa el cambio automático. Repite. Con ambos tiempos guardados, presiona otra vez el atajo principal para comparar y dar el punto automáticamente al menor tiempo.',ms:'Los milisegundos aparecen solamente aquí en la aplicación y se usan para desempatar. En el overlay quedan ocultos.',ready:'Listo para',timing:'Cronometrando',saved:'Tiempo guardado. Cambia a',savedAuto:'Tiempo guardado. Jugador cambiado automáticamente a',both:'Los dos tiempos están guardados. Presiona el atajo principal para comparar y puntuar.',winner:'Punto para',tie:'Empate exacto — sin punto.',setKey:'Haz clic y presiona una tecla…',internalConflict:'Esta tecla ya está usada por otro atajo',systemConflict:'No fue posible usar esa tecla. Puede estar reservada por Windows u otro programa.',autoSwap:'Cambiar jugador automáticamente al parar',autoSwapHint:'Activado: al guardar el primer tiempo, el otro jugador queda seleccionado automáticamente.',style0:'Vertical Edge',style1:'Vertical Core',style2:'Horizontal Line',style3:'Horizontal Split',style4:'Glass Arc',style5:'Glass Float',vertical:'Vertical',horizontal:'Horizontal',glass:'Glass'}
  };
  const t=()=>TX[lang]||TX.pt;
  const currentMs=p=>T?.running&&Number(T.runningPlayer)===p?Math.max(0,Date.now()-(Number(T.startedAt)||Date.now())):Math.max(0,Number(p===1?T?.time1:T?.time2)||0);
  const fmtApp=ms=>{ms=Math.max(0,Number(ms)||0);const total=Math.floor(ms/1000),m=Math.floor(total/60),s=total%60,milli=Math.floor(ms%1000);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(milli).padStart(3,'0')}`};
  const playerName=p=>p===1?(T?.player1||'PLAYER 1'):(T?.player2||'PLAYER 2');

  const style=document.createElement('style');
  style.textContent=`
  .timerPage{--tAccent:#22c55e}.timerHero{display:flex;align-items:center;gap:9px}.timerStatus{margin-left:auto;color:#9ca5b2;font-size:11px;text-align:right;max-width:620px}.timerPanel{background:#11151b;border:1px solid #2d333d;border-radius:11px;padding:10px;margin-bottom:8px;box-shadow:inset 0 1px rgba(255,255,255,.025)}.timerPanel h3{font-size:12px;margin:0 0 8px}.timerTopGrid{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(255px,.65fr);gap:8px}.timerPlayerGrid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.timerPlayer{display:grid;grid-template-columns:34px minmax(0,1fr);gap:7px;align-items:center;padding:7px 8px;border:1px solid #2d333d;border-radius:8px;background:#0e1116;cursor:pointer;position:relative;overflow:hidden;min-height:66px}.timerPlayer.active{border-color:var(--tAccent);box-shadow:0 0 0 1px color-mix(in srgb,var(--tAccent) 42%,transparent) inset}.timerPlayer.active:before{content:'';position:absolute;left:0;top:7px;bottom:7px;width:3px;border-radius:0 3px 3px 0;background:var(--tAccent)}.timerPill{display:flex;align-items:center;justify-content:center;height:28px;border-radius:6px;background:#303239;color:#fff;font-size:10px;font-weight:800}.timerPlayerMain{min-width:0}.timerPlayer input{width:100%;font-weight:700;min-height:29px;padding:4px 7px}.timerPlayerTime{display:block;margin-top:4px;text-align:right;font:800 11px/1 Consolas,monospace;color:#8d9099;letter-spacing:.3px}.timerPlayer.active .timerPlayerTime{color:var(--tAccent)}
  .timerScoreRow{display:flex;align-items:center;justify-content:center;gap:9px;padding:0}.timerScoreSide{display:flex;align-items:center;gap:4px}.timerScoreSide button{width:28px;min-width:28px;min-height:28px;padding:0;font-size:15px}.timerScoreNum{width:34px;text-align:center;font-size:22px;font-weight:900}.timerDash{color:#777b84;font-weight:900}.timerResetRow{display:flex;justify-content:center;margin-top:7px}.timerResetRow .danger{min-height:26px;padding:3px 9px;font-size:10px}
  .timerStyleGrid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:6px}.timerStyle{height:88px;text-align:center;background:#0e1116;border:1px solid #2c323c;border-radius:8px;padding:6px 5px;cursor:pointer;color:#eef2f7}.timerStyle.active{border-color:var(--tAccent);box-shadow:0 0 0 1px color-mix(in srgb,var(--tAccent) 45%,transparent) inset}.stylePreview{height:39px;display:flex;align-items:center;justify-content:center;position:relative}.stylePreview i{display:block;position:relative;background:#3c3f47;border:1px solid #737680}.stylePreview.s0 i{width:28px;height:36px;border-radius:4px;border-left:3px solid var(--tAccent)}.stylePreview.s1 i{width:31px;height:36px;border-radius:11px 4px 11px 4px}.stylePreview.s1 i:after{content:'';position:absolute;width:17px;height:3px;left:6px;top:16px;background:var(--tAccent)}.stylePreview.s2 i{width:76px;height:19px;border-radius:4px;border-bottom:3px solid var(--tAccent)}.stylePreview.s3 i{width:78px;height:21px;border-radius:5px}.stylePreview.s3 i:after{content:'';position:absolute;width:4px;height:21px;left:36px;top:-1px;background:var(--tAccent)}.stylePreview.s4 i{width:78px;height:24px;border-radius:14px;border-color:#aeb2bc;background:linear-gradient(100deg,#30333b99,#5b5f6990)}.stylePreview.s5 i{width:82px;height:18px;border-radius:999px;background:linear-gradient(90deg,#252832aa,#55596590);box-shadow:0 0 8px #000}.timerStyle b{display:block;font-size:10px;line-height:1.05;margin-top:4px}.timerStyle small{display:block;color:#8993a1;font-size:9px;margin-top:2px}
  .timerGrid2{display:grid;grid-template-columns:1.05fr .95fr;gap:8px}.timerHotkeyRow{display:grid;grid-template-columns:minmax(0,1fr) 145px 66px;gap:6px;align-items:center}.timerHotkeyRow+.timerHotkeyRow{margin-top:6px}.timerHotkeyLabel{border:1px solid #2c323c;background:#0e1116;border-radius:7px;padding:8px 9px;font-weight:600;font-size:11px}.timerKeyBtn{font-weight:900;min-height:34px;font-size:11px}.timerKeyReset{min-height:30px!important;padding:3px 7px!important;font-size:10px!important}.timerAutoSwap{margin-top:8px;border-top:1px solid #242a33;padding-top:8px}.timerAutoSwap label{display:flex;align-items:center;gap:7px;font-size:11px;font-weight:700}.timerAutoSwap input{width:16px;height:16px;min-height:0}.timerAutoSwap small{display:block;color:#8993a1;margin:4px 0 0 23px;font-size:10px}
  .timerRangeRow{display:grid;grid-template-columns:136px 1fr 55px;align-items:center;gap:8px;margin:6px 0}.timerRangeRow label{font-size:9px;font-weight:800;color:#858d9a;letter-spacing:.35px}.timerRangeRow output{text-align:center;border:1px solid #2e343e;border-radius:7px;padding:4px;background:#0e1116;font-weight:800;font-size:10px}.timerRangeRow input[type=range]{width:100%}.timerHint{color:#929ba8;font-size:10px;margin-top:6px}.timerColors{display:flex;align-items:center;gap:7px;flex-wrap:wrap;margin-top:8px}.timerSwatch{width:25px!important;height:25px!important;min-height:25px!important;padding:0!important;border-radius:6px!important;border:2px solid transparent!important}.timerSwatch.active{outline:2px solid #fff;outline-offset:1px}.timerSwatch.rainbow{background:linear-gradient(135deg,#ef4444 0 16%,#f97316 16% 32%,#facc15 32% 48%,#22c55e 48% 64%,#3b82f6 64% 80%,#a855f7 80% 100%)}.timerCustom{display:inline-flex;align-items:center;gap:5px;margin-left:2px;padding:3px 5px;border:1px solid #303742;border-radius:7px}.timerCustom span{font-size:9px;color:#aab3c0}.timerCustom input[type=color]{width:31px;height:25px;padding:1px}.timerWorkflow{line-height:1.45;padding-top:9px;padding-bottom:9px}.timerPrimary{border-color:var(--tAccent)!important}.timerPrimary.on{background:color-mix(in srgb,var(--tAccent) 16%,#161b22)!important}.rainbowAccent .timerPlayer.active:before{background:linear-gradient(#ef4444,#facc15,#22c55e,#3b82f6,#a855f7)}.rainbowAccent .timerStyle.active{border-color:#ec4899;box-shadow:0 0 0 1px #3b82f655 inset}
  body[data-ui-theme="light"] .timerPanel{background:#fff;border-color:#d7dee8;box-shadow:none}body[data-ui-theme="light"] .timerPlayer,body[data-ui-theme="light"] .timerStyle,body[data-ui-theme="light"] .timerHotkeyLabel,body[data-ui-theme="light"] .timerRangeRow output{background:#f7f9fb;border-color:#d7dee8}body[data-ui-theme="light"] .timerPlayerTime{color:#737d8a}
  @media(max-width:900px){.timerTopGrid,.timerGrid2{grid-template-columns:1fr}.timerStyleGrid{grid-template-columns:repeat(3,1fr)}.timerHotkeyRow{grid-template-columns:1fr 120px 62px}}
  `;
  document.head.appendChild(style);

  const nav=document.querySelector('.tabs');if(!nav)return;
  const tab=document.createElement('button');tab.dataset.tab='timer';tab.textContent='1V1 TIMER';nav.insertBefore(tab,nav.firstChild);
  const page=document.createElement('section');page.id='timer';page.className='page timerPage';
  page.innerHTML=`
    <div class="card timerHero"><button id="tm_enabledBtn" class="timerPrimary"></button><span id="tm_status" class="timerStatus"></span></div>
    <div class="timerTopGrid">
      <div class="timerPanel"><h3 id="tm_playersTitle"></h3><div class="timerPlayerGrid">
        <div id="tm_p1Card" class="timerPlayer"><span class="timerPill">P1</span><div class="timerPlayerMain"><input id="tm_player1" type="text" maxlength="48"><span id="tm_time1" class="timerPlayerTime">00:00.000</span></div></div>
        <div id="tm_p2Card" class="timerPlayer"><span class="timerPill">P2</span><div class="timerPlayerMain"><input id="tm_player2" type="text" maxlength="48"><span id="tm_time2" class="timerPlayerTime">00:00.000</span></div></div>
      </div></div>
      <div class="timerPanel"><h3 id="tm_scoreTitle"></h3><div class="timerScoreRow">
        <div class="timerScoreSide"><button id="tm_s1m">−</button><span id="tm_score1" class="timerScoreNum">0</span><button id="tm_s1p">+</button></div><span class="timerDash">–</span>
        <div class="timerScoreSide"><button id="tm_s2m">−</button><span id="tm_score2" class="timerScoreNum">0</span><button id="tm_s2p">+</button></div>
      </div><div class="timerResetRow"><button id="tm_reset" class="danger"></button></div></div>
    </div>
    <div class="timerPanel"><h3 id="tm_stylesTitle"></h3><div class="timerStyleGrid">
      ${[0,1,2,3,4,5].map(i=>`<button class="timerStyle" data-tm-style="${i}"><span class="stylePreview s${i}"><i></i></span><b id="tm_style${i}Name"></b><small id="tm_style${i}Type"></small></button>`).join('')}
    </div></div>
    <div class="timerGrid2">
      <div class="timerPanel"><h3 id="tm_hotkeysTitle"></h3>
        <div class="timerHotkeyRow"><div id="tm_actionLabel" class="timerHotkeyLabel"></div><button id="tm_actionKey" class="timerKeyBtn"></button><button id="tm_actionReset" class="danger timerKeyReset"></button></div>
        <div class="timerHotkeyRow"><div id="tm_swapLabel" class="timerHotkeyLabel"></div><button id="tm_swapKey" class="timerKeyBtn"></button><button id="tm_swapReset" class="danger timerKeyReset"></button></div>
        <div class="timerAutoSwap"><label><input id="tm_autoSwap" type="checkbox"><span id="tm_autoSwapLabel"></span></label><small id="tm_autoSwapHint"></small></div>
      </div>
      <div class="timerPanel"><h3 id="tm_appearanceTitle"></h3>
        <div class="timerRangeRow"><label id="tm_opacityLabel"></label><input id="tm_opacity" type="range" min="0" max="100" step="1"><output id="tm_opacityV"></output></div>
        <div class="timerRangeRow"><label id="tm_scaleLabel"></label><input id="tm_scale" type="range" min="70" max="110" step="1"><output id="tm_scaleV"></output></div>
        <div class="timerHint"><b id="tm_accentLabel"></b><div id="tm_accentHint"></div></div><div id="tm_colors" class="timerColors"></div>
      </div>
    </div>
    <div class="timerPanel timerWorkflow"><h3 id="tm_workflowTitle"></h3><div id="tm_workflowText"></div><div id="tm_workflowMs" class="timerHint"></div></div>`;
  const firstPage=document.querySelector('.page');firstPage.parentNode.insertBefore(page,firstPage);

  function openTimerTab(){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b===tab));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p===page))}
  tab.addEventListener('click',openTimerTab);openTimerTab();const version=document.querySelector('.brandVersion');if(version)version.textContent='Beta 2.0.0';

  function translate(){
    const d=t();tab.textContent=d.tab;$('tm_playersTitle').textContent=d.players;$('tm_scoreTitle').textContent=d.score;$('tm_stylesTitle').textContent=d.styles;$('tm_hotkeysTitle').textContent=d.hotkeys;$('tm_appearanceTitle').textContent=d.appearance;$('tm_reset').textContent=d.reset;$('tm_actionLabel').textContent=d.startStop;$('tm_swapLabel').textContent=d.swap;$('tm_actionReset').textContent=d.resetKey;$('tm_swapReset').textContent=d.resetKey;$('tm_opacityLabel').textContent=d.opacity;$('tm_scaleLabel').textContent=d.scale;$('tm_accentLabel').textContent=d.accent;$('tm_accentHint').textContent=d.accentHint;$('tm_autoSwapLabel').textContent=d.autoSwap;$('tm_autoSwapHint').textContent=d.autoSwapHint;$('tm_workflowTitle').textContent=d.workflow;$('tm_workflowText').textContent=d.workflowText;$('tm_workflowMs').textContent=d.ms;
    for(let i=0;i<6;i++)$(`tm_style${i}Name`).textContent=d[`style${i}`];
    ['vertical','vertical','horizontal','horizontal','glass','glass'].forEach((k,i)=>$(`tm_style${i}Type`).textContent=d[k]);
    buildColors();sync(T);
  }

  function buildColors(){
    if(!$('tm_colors'))return;
    $('tm_colors').innerHTML=SOLID_COLORS.map(([c,n])=>`<button class="timerSwatch" data-tm-color="${c}" style="background:${c}" title="${n}"></button>`).join('')+`<button class="timerSwatch rainbow" data-tm-rainbow="1" title="${t().rainbow}"></button><label class="timerCustom"><span>${t().custom}</span><input id="tm_customColor" type="color"></label>`;
    $('tm_colors').querySelectorAll('[data-tm-color]').forEach(b=>b.onclick=()=>api.timerPatch({accent:b.dataset.tmColor,accentMode:'solid'}));
    $('tm_colors').querySelector('[data-tm-rainbow]').onclick=()=>api.timerPatch({accentMode:'rainbow'});
    $('tm_customColor').addEventListener('input',e=>api.timerPatch({accent:e.target.value,accentMode:'solid'}));
  }

  function statusText(){
    if(!T)return'';const d=t();if(T.running)return `${d.timing} ${playerName(T.runningPlayer)}…`;if(T.done1&&T.done2)return d.both;if(T.lastWinner===1||T.lastWinner===2)return `${d.winner} ${playerName(T.lastWinner)}.`;if(T.lastWinner===3)return d.tie;const activeDone=T.active===1?T.done1:T.done2;if(activeDone){const other=T.active===1?2:1;return `${d.saved} ${playerName(other)}.`}const oneDone=T.done1!==T.done2;if(oneDone&&T.autoSwap)return `${d.savedAuto} ${playerName(T.active)}.`;return `${d.ready} ${playerName(T.active)}.`
  }

  function sync(s){
    if(!s)return;T=s;page.style.setProperty('--tAccent',T.accent||'#22c55e');page.classList.toggle('rainbowAccent',T.accentMode==='rainbow');
    if(document.activeElement!==$('tm_player1'))$('tm_player1').value=T.player1||'';if(document.activeElement!==$('tm_player2'))$('tm_player2').value=T.player2||'';
    $('tm_score1').textContent=T.score1||0;$('tm_score2').textContent=T.score2||0;$('tm_p1Card').classList.toggle('active',Number(T.active)!==2);$('tm_p2Card').classList.toggle('active',Number(T.active)===2);document.querySelectorAll('[data-tm-style]').forEach(b=>b.classList.toggle('active',Number(b.dataset.tmStyle)===Number(T.style)));
    $('tm_opacity').value=Math.round((Number(T.opacity)||0)*100);$('tm_opacityV').textContent=$('tm_opacity').value+'%';$('tm_scale').value=Number(T.scaleUi)||100;$('tm_scaleV').textContent=$('tm_scale').value+'%';$('tm_autoSwap').checked=!!T.autoSwap;
    $('tm_actionKey').textContent=capture==='action'?t().setKey:(T.hotkeyAction||'—');$('tm_swapKey').textContent=capture==='swap'?t().setKey:(T.hotkeySwap||'—');$('tm_actionReset').style.visibility=T.hotkeyAction?'visible':'hidden';$('tm_swapReset').style.visibility=T.hotkeySwap?'visible':'hidden';$('tm_enabledBtn').textContent=T.enabled?t().hide:t().show;$('tm_enabledBtn').classList.toggle('on',!!T.enabled);$('tm_status').textContent=statusText();
    const cc=$('tm_customColor');if(cc&&document.activeElement!==cc)cc.value=T.accent||'#22c55e';document.querySelectorAll('[data-tm-color]').forEach(b=>b.classList.toggle('active',T.accentMode!=='rainbow'&&(b.dataset.tmColor||'').toLowerCase()===(T.accent||'').toLowerCase()));const rb=document.querySelector('[data-tm-rainbow]');if(rb)rb.classList.toggle('active',T.accentMode==='rainbow');
  }

  function redrawTimes(){if(T){$('tm_time1').textContent=fmtApp(currentMs(1));$('tm_time2').textContent=fmtApp(currentMs(2))}requestAnimationFrame(redrawTimes)}
  $('tm_player1').addEventListener('input',e=>api.timerPatch({player1:e.target.value}));$('tm_player2').addEventListener('input',e=>api.timerPatch({player2:e.target.value}));$('tm_p1Card').addEventListener('click',e=>{if(e.target.tagName!=='INPUT')api.timerPatch({active:1})});$('tm_p2Card').addEventListener('click',e=>{if(e.target.tagName!=='INPUT')api.timerPatch({active:2})});
  $('tm_s1m').onclick=()=>api.timerScore(1,-1);$('tm_s1p').onclick=()=>api.timerScore(1,1);$('tm_s2m').onclick=()=>api.timerScore(2,-1);$('tm_s2p').onclick=()=>api.timerScore(2,1);$('tm_reset').onclick=async()=>sync(await api.timerReset());document.querySelectorAll('[data-tm-style]').forEach(b=>b.onclick=()=>api.timerPatch({style:+b.dataset.tmStyle}));$('tm_opacity').addEventListener('input',e=>{$('tm_opacityV').textContent=e.target.value+'%';api.timerPatch({opacity:+e.target.value/100})});$('tm_scale').addEventListener('input',e=>{$('tm_scaleV').textContent=e.target.value+'%';api.timerPatch({scaleUi:+e.target.value})});$('tm_enabledBtn').onclick=()=>api.timerPatch({enabled:!T.enabled});$('tm_autoSwap').onchange=e=>api.timerPatch({autoSwap:e.target.checked});

  function accelerator(e){const mods=[];if(e.ctrlKey)mods.push('Control');if(e.altKey)mods.push('Alt');if(e.shiftKey)mods.push('Shift');if(e.metaKey)mods.push('Super');let k=e.key;if(['Control','Alt','Shift','Meta'].includes(k))return'';if(k===' ')k='Space';if(k.length===1)k=k.toUpperCase();return [...mods,k].join('+')}
  $('tm_actionKey').onclick=()=>{capture='action';sync(T)};$('tm_swapKey').onclick=()=>{capture='swap';sync(T)};$('tm_actionReset').onclick=async()=>{capture=null;const r=await api.timerHotkey('action','');sync(r.state)};$('tm_swapReset').onclick=async()=>{capture=null;const r=await api.timerHotkey('swap','');sync(r.state)};
  addEventListener('keydown',async e=>{if(!capture)return;e.preventDefault();e.stopImmediatePropagation();if(e.key==='Escape'){capture=null;sync(T);return}const key=accelerator(e);if(!key)return;const which=capture,owner=which==='swap'?'timer.swap':'timer.action';capture=null;const conflict=api.checkHotkeyConflict?await api.checkHotkeyConflict(key,owner):{conflict:false};if(conflict?.conflict){alert(`${t().internalConflict}: ${conflict.label}.`);sync(T);return}const r=await api.timerHotkey(which,key);T=r.state;if(!r.ok)alert(r.reason==='internal'?`${t().internalConflict}${r.conflict?`: ${r.conflict}`:''}.`:t().systemConflict);sync(T)},true);

  api.onTimerState(sync);api.onState?.(s=>{if(s?.language&&s.language!==lang){lang=s.language;translate()}});
  (async()=>{const root=await api.get();lang=root?.state?.language||'pt';const x=await api.timerGet();T=x.state;buildColors();translate();sync(T);redrawTimes()})();
})();
