(()=>{
  'use strict';

  const SOLID_COLORS=[
    ['#22c55e','Verde'],['#facc15','Amarelo'],['#3b82f6','Azul'],['#ef4444','Vermelho'],
    ['#ec4899','Rosa'],['#a855f7','Roxo'],['#06b6d4','Ciano'],['#f97316','Laranja']
  ];
  const DEFAULT_KEYS={action:'F1',swap:'F2'};
  let T=null,lang='pt',capture=null;
  const $=id=>document.getElementById(id);

  const TX={
    pt:{tab:'1V1 TIMER',show:'Mostrar overlay',hide:'Ocultar overlay',players:'Players',score:'Placar',styles:'Estilos',hotkeys:'Atalhos do 1v1 Timer',appearance:'Aparência',reset:'Resetar partida',startStop:'Iniciar / Parar / Pontuar',swap:'Trocar player',resetKey:'Resetar',opacity:'OPACIDADE DO FUNDO',scale:'ESCALA',accent:'Cor de destaque',accentHint:'A cor aparece apenas no traço e no cronômetro do player ativo. Os nomes permanecem brancos.',custom:'Personalizado',workflow:'Como funciona',workflowText:'O atalho principal inicia o player selecionado. Pressione de novo para parar e salvar o tempo. Troque para o outro player pelo segundo atalho, ou ative a troca automática. Com os dois tempos salvos, pressione novamente o atalho principal para comparar e dar o ponto ao menor tempo.',ms:'Os milissegundos aparecem somente aqui no aplicativo e continuam sendo usados para desempatar. No overlay ficam ocultos.',ready:'Pronto para',timing:'Cronometrando',saved:'Tempo salvo. Troque para',savedAuto:'Tempo salvo. Próximo player selecionado:',both:'Os dois tempos estão salvos. Pressione o atalho principal para comparar e pontuar.',winner:'Ponto para',tie:'Empate exato — nenhum ponto.',setKey:'Clique e pressione uma tecla ou botão do mouse…',internalConflict:'Esse botão já existe em outro atalho',systemConflict:'Não foi possível usar esse atalho. Ele pode estar reservado pelo Windows ou por outro programa.',autoSwap:'Trocar player automaticamente ao parar',autoSwapHint:'Ativado: você usa apenas o atalho principal para iniciar, parar, iniciar o outro player, parar e pontuar.',style0:'Side Stack',style1:'Split Tower',style2:'Center Beam',style3:'Corner Rail',style4:'Glass Wings',style5:'Glass Ribbon',vertical:'Vertical',horizontal:'Horizontal',glass:'Glass'},
    en:{tab:'1V1 TIMER',show:'Show overlay',hide:'Hide overlay',players:'Players',score:'Score',styles:'Styles',hotkeys:'1v1 Timer Hotkeys',appearance:'Appearance',reset:'Reset match',startStop:'Start / Stop / Score',swap:'Swap player',resetKey:'Reset',opacity:'BACKGROUND OPACITY',scale:'SCALE',accent:'Accent color',accentHint:'The accent appears only on the active player rail and timer. Player names stay white.',custom:'Custom',workflow:'How it works',workflowText:'The main shortcut starts the selected player. Press it again to stop and save the time. Swap to the other player with the second shortcut, or enable automatic swapping. With both times saved, press the main shortcut again to compare and award the point to the faster time.',ms:'Milliseconds are shown only here in the app and are still used as the tiebreaker. They stay hidden on the overlay.',ready:'Ready for',timing:'Timing',saved:'Time saved. Swap to',savedAuto:'Time saved. Next player selected:',both:'Both times are saved. Press the main shortcut to compare and score.',winner:'Point for',tie:'Exact tie — no point.',setKey:'Click and press a key or mouse button…',internalConflict:'This button is already used by another shortcut',systemConflict:'Could not use that shortcut. It may be reserved by Windows or another program.',autoSwap:'Automatically swap player when stopped',autoSwapHint:'On: use only the main shortcut to start, stop, start the other player, stop and score.',style0:'Side Stack',style1:'Split Tower',style2:'Center Beam',style3:'Corner Rail',style4:'Glass Wings',style5:'Glass Ribbon',vertical:'Vertical',horizontal:'Horizontal',glass:'Glass'},
    es:{tab:'1V1 TIMER',show:'Mostrar overlay',hide:'Ocultar overlay',players:'Jugadores',score:'Marcador',styles:'Estilos',hotkeys:'Atajos del 1v1 Timer',appearance:'Apariencia',reset:'Reiniciar partida',startStop:'Iniciar / Parar / Puntuar',swap:'Cambiar jugador',resetKey:'Reiniciar',opacity:'OPACIDAD DEL FONDO',scale:'ESCALA',accent:'Color de destaque',accentHint:'El color aparece solo en la línea y el cronómetro del jugador activo. Los nombres permanecen blancos.',custom:'Personalizado',workflow:'Cómo funciona',workflowText:'El atajo principal inicia al jugador seleccionado. Presiónalo otra vez para parar y guardar el tiempo. Cambia al otro jugador con el segundo atajo, o activa el cambio automático. Con ambos tiempos guardados, presiona de nuevo el atajo principal para comparar y dar el punto al menor tiempo.',ms:'Los milisegundos aparecen solamente aquí en la aplicación y se usan para desempatar. En el overlay quedan ocultos.',ready:'Listo para',timing:'Cronometrando',saved:'Tiempo guardado. Cambia a',savedAuto:'Tiempo guardado. Próximo jugador seleccionado:',both:'Los dos tiempos están guardados. Presiona el atajo principal para comparar y puntuar.',winner:'Punto para',tie:'Empate exacto — sin punto.',setKey:'Haz clic y presiona una tecla o botón del mouse…',internalConflict:'Este botón ya está usado por otro atajo',systemConflict:'No fue posible usar ese atajo. Puede estar reservado por Windows u otro programa.',autoSwap:'Cambiar jugador automáticamente al parar',autoSwapHint:'Activado: usa solo el atajo principal para iniciar, parar, iniciar al otro jugador, parar y puntuar.',style0:'Side Stack',style1:'Split Tower',style2:'Center Beam',style3:'Corner Rail',style4:'Glass Wings',style5:'Glass Ribbon',vertical:'Vertical',horizontal:'Horizontal',glass:'Glass'}
  };
  const t=()=>TX[lang]||TX.pt;
  const currentMs=p=>T?.running&&Number(T.runningPlayer)===p?Math.max(0,Date.now()-(Number(T.startedAt)||Date.now())):Math.max(0,Number(p===1?T?.time1:T?.time2)||0);
  const fmtApp=ms=>{ms=Math.max(0,Number(ms)||0);const total=Math.floor(ms/1000),m=Math.floor(total/60),s=total%60,milli=Math.floor(ms%1000);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(milli).padStart(3,'0')}`};
  const playerName=p=>p===1?(T?.player1||'PLAYER 1'):(T?.player2||'PLAYER 2');

  const style=document.createElement('style');
  style.textContent=`
  .timerPage{--tAccent:#22c55e}.timerHero{display:flex;align-items:center;gap:9px}.timerStatus{margin-left:auto;color:#9ca5b2;font-size:11px;text-align:right;max-width:620px}.timerPanel{background:#11151b;border:1px solid #2d333d;border-radius:10px;padding:9px;margin-bottom:7px;box-shadow:inset 0 1px rgba(255,255,255,.025)}.timerPanel h3{font-size:12px;margin:0 0 7px}.timerTopGrid{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(235px,.55fr);gap:7px}.timerPlayerGrid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.timerPlayer{display:grid;grid-template-columns:32px minmax(0,1fr);gap:7px;align-items:center;padding:6px 8px;border:1px solid #2d333d;border-radius:8px;background:#0e1116;cursor:pointer;position:relative;overflow:hidden;min-height:60px}.timerPlayer.active{border-color:var(--tAccent);box-shadow:0 0 0 1px color-mix(in srgb,var(--tAccent) 38%,transparent) inset}.timerPlayer.active:before{content:'';position:absolute;left:0;top:7px;bottom:7px;width:3px;border-radius:0 3px 3px 0;background:var(--tAccent)}.timerPill{display:flex;align-items:center;justify-content:center;height:26px;border-radius:6px;background:#303239;color:#fff;font-size:10px;font-weight:800}.timerPlayerMain{min-width:0}.timerPlayer input{width:100%;font-weight:700;min-height:28px;padding:3px 7px}.timerPlayerTime{display:block;margin-top:3px;text-align:right;font:800 11px/1 Consolas,monospace;color:#8d9099;letter-spacing:.3px}.timerPlayer.active .timerPlayerTime{color:var(--tAccent)}
  .timerScoreRow{display:flex;align-items:center;justify-content:center;gap:8px}.timerScoreSide{display:flex;align-items:center;gap:3px}.timerScoreSide button{width:33px;min-width:33px;min-height:33px;padding:0;font-size:18px;font-weight:900}.timerScoreNum{width:40px;text-align:center;font-size:27px;font-weight:950}.timerDash{color:#777b84;font-weight:900}.timerResetRow{display:flex;justify-content:center;margin-top:6px}.timerResetRow .danger{min-height:25px;padding:2px 8px;font-size:10px}
  .timerStyleGrid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:5px}.timerStyle{height:84px;text-align:center;background:#0e1116;border:1px solid #2c323c;border-radius:7px;padding:5px 4px;cursor:pointer;color:#eef2f7}.timerStyle.active{border-color:var(--tAccent);box-shadow:0 0 0 1px color-mix(in srgb,var(--tAccent) 42%,transparent) inset}.stylePreview{height:37px;display:flex;align-items:center;justify-content:center;position:relative}.stylePreview i{display:block;position:relative;background:#30343c;border:1px solid #747985}.stylePreview.s0 i{width:30px;height:35px;clip-path:polygon(0 0,100% 0,100% 77%,78% 100%,0 100%);border-left:3px solid var(--tAccent)}.stylePreview.s1 i{width:33px;height:34px;border-radius:3px;background:linear-gradient(#30343c 0 42%,transparent 42% 56%,#30343c 56% 100%)}.stylePreview.s1 i:after{content:'';position:absolute;left:6px;right:6px;top:16px;height:2px;background:var(--tAccent)}.stylePreview.s2 i{width:78px;height:17px;clip-path:polygon(6px 0,calc(100% - 6px) 0,100% 50%,calc(100% - 6px) 100%,6px 100%,0 50%)}.stylePreview.s2 i:after{content:'';position:absolute;left:10px;right:10px;bottom:0;height:2px;background:var(--tAccent)}.stylePreview.s3 i{width:78px;height:20px;border-radius:2px;border-top:2px solid var(--tAccent);border-bottom:2px solid #ffffff22}.stylePreview.s4 i{width:80px;height:23px;border:0;background:linear-gradient(90deg,#4d515a88 0 36%,transparent 36% 64%,#4d515a88 64% 100%);border-radius:11px}.stylePreview.s5 i{width:82px;height:17px;border-radius:3px;clip-path:polygon(6px 0,100% 0,calc(100% - 6px) 100%,0 100%);background:linear-gradient(90deg,#34384188,#585d6688,#34384188)}.timerStyle b{display:block;font-size:9.5px;line-height:1.05;margin-top:4px}.timerStyle small{display:block;color:#8993a1;font-size:8.5px;margin-top:2px}
  .timerGrid2{display:grid;grid-template-columns:1.06fr .94fr;gap:7px}.timerHotkeyRow{display:grid;grid-template-columns:minmax(0,1fr) 142px 64px;gap:5px;align-items:center}.timerHotkeyRow+.timerHotkeyRow{margin-top:5px}.timerHotkeyLabel{border:1px solid #2c323c;background:#0e1116;border-radius:7px;padding:7px 9px;font-weight:700}.timerKeyBtn{font-weight:900;letter-spacing:.3px}.timerKeyReset{font-size:10px;padding:3px 6px;min-height:28px}.timerAutoSwap{margin-top:8px;padding:9px 10px;border:1px solid #343c48;border-radius:9px;background:#0d1117;transition:border-color .15s ease,box-shadow .15s ease}.timerAutoSwap:has(input:checked){border-color:var(--tAccent);box-shadow:0 0 0 1px color-mix(in srgb,var(--tAccent) 36%,transparent) inset,0 0 14px color-mix(in srgb,var(--tAccent) 12%,transparent)}.timerAutoSwap label{display:flex;align-items:center;gap:9px;font-weight:800;cursor:pointer}.timerAutoSwap input{appearance:none;-webkit-appearance:none;width:40px;height:22px;min-height:22px;border:1px solid #505965;border-radius:999px;background:#242a33;position:relative;padding:0;cursor:pointer;flex:0 0 auto;transition:.15s}.timerAutoSwap input:after{content:'';position:absolute;width:16px;height:16px;border-radius:50%;background:#d6dae0;left:2px;top:2px;box-shadow:0 1px 4px #0008;transition:.15s}.timerAutoSwap input:checked{background:var(--tAccent);border-color:var(--tAccent)}.timerAutoSwap input:checked:after{transform:translateX(18px);background:#fff}.timerAutoSwap small{display:block;color:#9aa4b2;margin:5px 0 0 49px;line-height:1.3}.timerRangeRow{display:grid;grid-template-columns:145px 1fr 45px;gap:7px;align-items:center;margin-bottom:7px}.timerRangeRow label{font-size:10px;color:#8f98a6;font-weight:800}.timerRangeRow input{width:100%}.timerRangeRow output{text-align:right;font-weight:800}.timerHint{font-size:10px;color:#8e98a7}.timerColors{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-top:9px}.timerSwatch{width:42px;height:32px;min-height:32px;padding:0;border-radius:10px 4px 10px 4px;border:2px solid #ffffff24;box-shadow:inset 0 1px rgba(255,255,255,.2),0 3px 8px #0004;transition:transform .12s,border-color .12s}.timerSwatch:hover{transform:translateY(-1px);border-color:#ffffff70}.timerSwatch.active{outline:2px solid #fff;outline-offset:2px}.timerCustom{display:flex;align-items:center;gap:8px;border:1px solid #3b4451;border-radius:10px;padding:5px 8px;font-size:10px;font-weight:800;background:#0d1117}.timerCustom input{width:42px;height:30px;min-height:30px;padding:1px;border-radius:7px;cursor:pointer}.timerWorkflow{font-size:11px;color:#c6ccd5}.timerWorkflow h3{color:#fff}.timerWorkflow .timerHint{margin-top:4px}.timerPage input[type=range]{accent-color:var(--tAccent)}
  body[data-ui-theme="light"] .timerPanel{background:#fff;border-color:#d5dde7}body[data-ui-theme="light"] .timerPlayer,body[data-ui-theme="light"] .timerStyle,body[data-ui-theme="light"] .timerHotkeyLabel{background:#f5f7fa;border-color:#d0d8e2;color:#1d2732}body[data-ui-theme="midnight"] .timerPanel{background:#0d1828;border-color:#1c3150}body[data-ui-theme="violet"] .timerPanel{background:#1b1423;border-color:#352641}
  @media(max-width:900px){.timerStyleGrid{grid-template-columns:repeat(3,1fr)}.timerTopGrid,.timerGrid2{grid-template-columns:1fr}}
  `;
  document.head.appendChild(style);

  const nav=document.querySelector('.tabs');
  if(!nav||document.getElementById('timer'))return;
  const tab=document.createElement('button');tab.dataset.tab='timer';nav.insertBefore(tab,nav.firstChild);
  const page=document.createElement('section');page.id='timer';page.className='page timerPage';
  page.innerHTML=`
    <div class="timerPanel"><div class="timerHero"><button id="tm_enabledBtn" class="bigToggle"></button><div id="tm_status" class="timerStatus"></div></div></div>
    <div class="timerTopGrid">
      <div class="timerPanel"><h3 id="tm_playersTitle"></h3><div class="timerPlayerGrid">
        <div id="tm_p1Card" class="timerPlayer"><span class="timerPill">P1</span><div class="timerPlayerMain"><input id="tm_player1" maxlength="48"><span id="tm_time1" class="timerPlayerTime">00:00.000</span></div></div>
        <div id="tm_p2Card" class="timerPlayer"><span class="timerPill">P2</span><div class="timerPlayerMain"><input id="tm_player2" maxlength="48"><span id="tm_time2" class="timerPlayerTime">00:00.000</span></div></div>
      </div></div>
      <div class="timerPanel"><h3 id="tm_scoreTitle"></h3><div class="timerScoreRow"><div class="timerScoreSide"><button id="tm_s1m">−</button><span id="tm_score1" class="timerScoreNum">0</span><button id="tm_s1p">+</button></div><span class="timerDash">—</span><div class="timerScoreSide"><button id="tm_s2m">−</button><span id="tm_score2" class="timerScoreNum">0</span><button id="tm_s2p">+</button></div></div><div class="timerResetRow"><button id="tm_reset" class="danger"></button></div></div>
    </div>
    <div class="timerPanel"><h3 id="tm_stylesTitle"></h3><div class="timerStyleGrid">
      ${[0,1,2,3,4,5].map(i=>`<button class="timerStyle" data-tm-style="${i}"><span class="stylePreview s${i}"><i></i></span><b id="tm_style${i}Name"></b><small id="tm_style${i}Type"></small></button>`).join('')}
    </div></div>
    <div class="timerGrid2">
      <div class="timerPanel"><h3 id="tm_hotkeysTitle"></h3>
        <div class="timerHotkeyRow"><div id="tm_actionLabel" class="timerHotkeyLabel"></div><button id="tm_actionKey" class="timerKeyBtn"></button><button id="tm_actionReset" class="danger timerKeyReset"></button></div>
        <div class="timerHotkeyRow"><div id="tm_swapLabel" class="timerHotkeyLabel"></div><button id="tm_swapKey" class="timerKeyBtn"></button><button id="tm_swapReset" class="danger timerKeyReset"></button></div>
        <div class="timerAutoSwap"><label><input id="tm_autoSwap" type="checkbox"><span id="tm_autoSwapLabel"></span></label><small id="tm_autoSwapHint"></small></div>
      </div>
      <div class="timerPanel"><h3 id="tm_appearanceTitle"></h3>
        <div class="timerRangeRow"><label id="tm_opacityLabel"></label><input id="tm_opacity" type="range" min="0" max="100" step="1"><output id="tm_opacityV"></output></div>
        <div class="timerRangeRow"><label id="tm_scaleLabel"></label><input id="tm_scale" type="range" min="70" max="100" step="1"><output id="tm_scaleV"></output></div>
        <div class="timerHint"><b id="tm_accentLabel"></b><div id="tm_accentHint"></div></div><div id="tm_colors" class="timerColors"></div>
      </div>
    </div>
    <div class="timerPanel timerWorkflow"><h3 id="tm_workflowTitle"></h3><div id="tm_workflowText"></div><div id="tm_workflowMs" class="timerHint"></div></div>`;
  const firstPage=document.querySelector('.page');firstPage.parentNode.insertBefore(page,firstPage);

  function openTimerTab(){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b===tab));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p===page))}
  tab.addEventListener('click',openTimerTab);openTimerTab();const version=document.querySelector('.brandVersion');if(version)version.textContent='Beta 2.0.1';

  function translate(){
    const d=t();tab.textContent=d.tab;$('tm_playersTitle').textContent=d.players;$('tm_scoreTitle').textContent=d.score;$('tm_stylesTitle').textContent=d.styles;$('tm_hotkeysTitle').textContent=d.hotkeys;$('tm_appearanceTitle').textContent=d.appearance;$('tm_reset').textContent=d.reset;$('tm_actionLabel').textContent=d.startStop;$('tm_swapLabel').textContent=d.swap;$('tm_actionReset').textContent=d.resetKey;$('tm_swapReset').textContent=d.resetKey;$('tm_opacityLabel').textContent=d.opacity;$('tm_scaleLabel').textContent=d.scale;$('tm_accentLabel').textContent=d.accent;$('tm_accentHint').textContent=d.accentHint;$('tm_autoSwapLabel').textContent=d.autoSwap;$('tm_autoSwapHint').textContent=d.autoSwapHint;$('tm_workflowTitle').textContent=d.workflow;$('tm_workflowText').textContent=d.workflowText;$('tm_workflowMs').textContent=d.ms;
    for(let i=0;i<6;i++)$(`tm_style${i}Name`).textContent=d[`style${i}`];
    ['vertical','vertical','horizontal','horizontal','glass','glass'].forEach((k,i)=>$(`tm_style${i}Type`).textContent=d[k]);
    buildColors();sync(T);
  }

  function buildColors(){
    if(!$('tm_colors'))return;
    $('tm_colors').innerHTML=SOLID_COLORS.map(([c,n])=>`<button class="timerSwatch" data-tm-color="${c}" style="background:${c}" title="${n}"></button>`).join('')+`<label class="timerCustom"><span>${t().custom}</span><input id="tm_customColor" type="color"></label>`;
    $('tm_colors').querySelectorAll('[data-tm-color]').forEach(b=>b.onclick=()=>api.timerPatch({accent:b.dataset.tmColor,accentMode:'solid'}));
    $('tm_customColor').addEventListener('input',e=>api.timerPatch({accent:e.target.value,accentMode:'solid'}));
  }

  function statusText(){
    if(!T)return'';const d=t();if(T.running)return `${d.timing} ${playerName(T.runningPlayer)}…`;if(T.done1&&T.done2)return d.both;if(T.lastWinner===1||T.lastWinner===2)return `${d.winner} ${playerName(T.lastWinner)}.`;if(T.lastWinner===3)return d.tie;const activeDone=T.active===1?T.done1:T.done2;if(activeDone){const other=T.active===1?2:1;return `${d.saved} ${playerName(other)}.`}const oneDone=T.done1!==T.done2;if(oneDone&&T.autoSwap)return `${d.savedAuto} ${playerName(T.active)}.`;return `${d.ready} ${playerName(T.active)}.`
  }

  function sync(s){
    if(!s)return;T=s;page.style.setProperty('--tAccent',T.accent||'#22c55e');
    if(document.activeElement!==$('tm_player1'))$('tm_player1').value=T.player1||'';if(document.activeElement!==$('tm_player2'))$('tm_player2').value=T.player2||'';
    $('tm_score1').textContent=T.score1||0;$('tm_score2').textContent=T.score2||0;$('tm_p1Card').classList.toggle('active',Number(T.active)!==2);$('tm_p2Card').classList.toggle('active',Number(T.active)===2);document.querySelectorAll('[data-tm-style]').forEach(b=>b.classList.toggle('active',Number(b.dataset.tmStyle)===Number(T.style)));
    $('tm_opacity').value=Math.round((Number(T.opacity)||0)*100);$('tm_opacityV').textContent=$('tm_opacity').value+'%';$('tm_scale').value=Math.min(100,Number(T.scaleUi)||100);$('tm_scaleV').textContent=$('tm_scale').value+'%';$('tm_autoSwap').checked=!!T.autoSwap;
    $('tm_actionKey').textContent=capture==='action'?t().setKey:(T.hotkeyAction||DEFAULT_KEYS.action);$('tm_swapKey').textContent=capture==='swap'?t().setKey:(T.hotkeySwap||DEFAULT_KEYS.swap);$('tm_actionReset').style.visibility=(T.hotkeyAction||DEFAULT_KEYS.action)!==DEFAULT_KEYS.action?'visible':'hidden';$('tm_swapReset').style.visibility=(T.hotkeySwap||DEFAULT_KEYS.swap)!==DEFAULT_KEYS.swap?'visible':'hidden';$('tm_enabledBtn').textContent=T.enabled?t().hide:t().show;$('tm_enabledBtn').classList.toggle('on',!!T.enabled);$('tm_status').textContent=statusText();
    const cc=$('tm_customColor');if(cc&&document.activeElement!==cc)cc.value=T.accent||'#22c55e';document.querySelectorAll('[data-tm-color]').forEach(b=>b.classList.toggle('active',(b.dataset.tmColor||'').toLowerCase()===(T.accent||'').toLowerCase()));
  }

  function redrawTimes(){if(T){$('tm_time1').textContent=fmtApp(currentMs(1));$('tm_time2').textContent=fmtApp(currentMs(2))}requestAnimationFrame(redrawTimes)}
  $('tm_player1').addEventListener('input',e=>api.timerPatch({player1:e.target.value}));$('tm_player2').addEventListener('input',e=>api.timerPatch({player2:e.target.value}));$('tm_p1Card').addEventListener('click',e=>{if(e.target.tagName!=='INPUT')api.timerPatch({active:1})});$('tm_p2Card').addEventListener('click',e=>{if(e.target.tagName!=='INPUT')api.timerPatch({active:2})});
  $('tm_s1m').onclick=()=>api.timerScore(1,-1);$('tm_s1p').onclick=()=>api.timerScore(1,1);$('tm_s2m').onclick=()=>api.timerScore(2,-1);$('tm_s2p').onclick=()=>api.timerScore(2,1);$('tm_reset').onclick=async()=>sync(await api.timerReset());document.querySelectorAll('[data-tm-style]').forEach(b=>b.onclick=()=>api.timerPatch({style:+b.dataset.tmStyle}));$('tm_opacity').addEventListener('input',e=>{$('tm_opacityV').textContent=e.target.value+'%';api.timerPatch({opacity:+e.target.value/100})});$('tm_scale').addEventListener('input',e=>{$('tm_scaleV').textContent=e.target.value+'%';api.timerPatch({scaleUi:+e.target.value})});$('tm_enabledBtn').onclick=()=>api.timerPatch({enabled:!T.enabled});$('tm_autoSwap').onchange=e=>api.timerPatch({autoSwap:e.target.checked});

  function accelerator(e){const mods=[];if(e.ctrlKey)mods.push('Control');if(e.altKey)mods.push('Alt');if(e.shiftKey)mods.push('Shift');if(e.metaKey)mods.push('Super');let k=e.key;if(['Control','Alt','Shift','Meta'].includes(k))return'';if(k===' ')k='Space';if(k.length===1)k=k.toUpperCase();return [...mods,k].join('+')}
  function mouseAccelerator(e){if(e.button===1)return'MOUSE3';if(e.button===3)return'MOUSE4';if(e.button===4)return'MOUSE5';return''}
  async function commitShortcut(which,key){if(!key)return;const owner=which==='swap'?'timer.swap':'timer.action';capture=null;const conflict=api.checkHotkeyConflict?await api.checkHotkeyConflict(key,owner):{conflict:false};if(conflict?.conflict){alert(`${t().internalConflict}: ${conflict.label}.`);sync(T);return}const r=await api.timerHotkey(which,key);T=r.state;if(!r.ok)alert(r.reason==='internal'?`${t().internalConflict}${r.conflict?`: ${r.conflict}`:''}.`:t().systemConflict);sync(T)}
  $('tm_actionKey').onclick=()=>{capture='action';sync(T)};$('tm_swapKey').onclick=()=>{capture='swap';sync(T)};
  $('tm_actionReset').onclick=async()=>commitShortcut('action',DEFAULT_KEYS.action);$('tm_swapReset').onclick=async()=>commitShortcut('swap',DEFAULT_KEYS.swap);
  addEventListener('keydown',async e=>{if(!capture)return;e.preventDefault();e.stopImmediatePropagation();if(e.key==='Escape'){capture=null;sync(T);return}const key=accelerator(e);if(key)await commitShortcut(capture,key)},true);
  addEventListener('mousedown',async e=>{if(!capture)return;const key=mouseAccelerator(e);if(!key)return;e.preventDefault();e.stopImmediatePropagation();await commitShortcut(capture,key)},true);

  api.onTimerState(sync);api.onState?.(s=>{if(s?.language&&s.language!==lang){lang=s.language;translate()}});
  (async()=>{const root=await api.get();lang=root?.state?.language||'pt';const x=await api.timerGet();T=x.state;buildColors();translate();sync(T);redrawTimes()})();
})();
